import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import productsRouter from "./products.js";
import ordersRouter from "./orders.js";
import analyticsRouter from "./analytics.js";
import newsletterRouter from "./newsletter.js";
import settingsRouter from "./settings.js";
import couponsRouter from "./coupons.js";

const router: IRouter = Router();
router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/products", productsRouter);
router.use("/orders", ordersRouter);
router.use("/analytics", analyticsRouter);
router.use("/newsletter", newsletterRouter);
router.use("/admin/settings", settingsRouter);
router.use("/admin/coupons", couponsRouter);
export default router;
